### PR TITLE
chore: fix Node.js TOC for cloud-rad

### PR DESCRIPTION
**Pull request by fhinkel**

### CODE REVIEW

**Review by SurferJeffAtGoogle — APPROVED** [review]

**Comment by bcoe** [comment]
I think this will result in 100 PRs without context tomorrow morning, due to landing [this](https://github.com/googleapis/synthtool/commit/f96d3b455fe27c3dc7bc37c3c9cd27b1c6d269c8) on the same day.

@SurferJeffAtGoogle any advice to make this less of a pain?

**Comment by SurferJeffAtGoogle** [comment]
They'll have context, but because there will be two commits in the PR, the
PR title will be "Changes due to synthtool," yadayada.

If you'd like to avoid that, visit fusion and trigger all 10 nodejs shards
to rebuild.  Merge the generated PRs, then merge this PR.

**Comment by fhinkel** [comment]
Or we can wait a few days before we merge this? Sorry for the confusion. Of course I don't get a `sed` regex right on the first try.

**Comment by bcoe** [comment]
@SurferJeffAtGoogle @fhinkel why don't we just make sure at the end of the day today, that there are no PRs open with the title "Changes due to synthtool".

Then we can merge this, and tomorrow morning rename all the PRs?

**Comment by SurferJeffAtGoogle** [comment]
That's fine too.  But clicking all the jobs in fusion is pretty easy: 2
clicks for each shard, and it's done.  And it's no different from a nightly
run.

**Review by JustinBeckwith — APPROVED** [review]

**Pull request merged**
