### PR TITLE
ci: automatic kokoro label in and /gcbrun comment

### PR DESCRIPTION
**Pull request by suztomo**
From reading the configuration (https://github.com/googleapis/repo-automation-bots/pull/1682/files), it accepts multiple objects.

### CODE REVIEW

**Review by chingor13 — APPROVED** [review]

**Comment by blakeli0** [comment]
Do we expect this change to be propagated to all libraries through Owlbot PRs?

**Comment by suztomo** [comment]
> Do we expect this change to be propagated to all libraries through Owlbot PRs?

Yes.

**Comment by blakeli0** [comment]
> > Do we expect this change to be propagated to all libraries through Owlbot PRs?
> 
> Yes.

Thanks! I don't see this file `trusted-contribution.yml` in google-cloud-java, is it excluded in some steps?

**Comment by suztomo** [comment]
>  I don't see this file trusted-contribution.yml in google-cloud-java, is it excluded in some steps?

There's no OwlBot configuration for google-cloud-java any more https://github.com/googleapis/google-cloud-java/tree/main/.github. Thus the postprocessor does not run.

**Comment by suztomo** [comment]
The file was not there before the monorepo migraiton https://github.com/googleapis/google-cloud-java/tree/main_202208/.github.

> so this file should at least exist in google-cloud-java

What observations made you think that?

**Comment by suztomo** [comment]
The postprocessor had been running, but owlbot-java has special treatment not to process the root directory of google-cloud-java.

**Review by blakeli0 — APPROVED** [review]
LGTM. @diegomarquezp We need to add these templates to hermetic build as well.

**Pull request merged**
