### PR TITLE
chore: update requirements.txt to address dependabot security alerts

### PR DESCRIPTION
**Pull request by alicejli**
Created by running:
` pip-compile requirements.in --generate-hashes --upgrade` within `synthtool/docker/owlbot/java/src/` as well as `synthtool/gcp/templates/java_library/.kokoro`

Closes https://github.com/googleapis/synthtool/pull/1830

Closes https://github.com/googleapis/synthtool/pull/1802

Closes https://github.com/googleapis/synthtool/pull/1801

### CODE REVIEW

**Comment by alicejli** [comment]
Kokoro check failing:
```
Executing: docker run --rm --interactive --network=host --privileged --volume=/var/run/docker.sock:/var/run/docker.sock --workdir=/tmpfs/src --entrypoint=github/synthtool/.kokoro/build.sh --env-file=/tmpfs/tmp/tmph267ibdj/envfile --volume=/tmpfs:/tmpfs gcr.io/cloud-devrel-kokoro-resources/python
nox > Running session lint-3.6
nox > Creating virtual environment (virtualenv) using python3.6 in .nox/lint-3-6
nox > Command /usr/local/bin/python3 -m virtualenv /tmpfs/src/github/synthtool/.nox/lint-3-6 -p python3.6 failed with exit code 1:
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'
nox > Session lint-3.6 failed.
nox > Running session lint-3.10
nox > Missing interpreters will error by default on CI systems.
nox > Session lint-3.10 skipped: Python interpreter 3.10 not found.
nox > Running session test-3.6
nox > Creating virtual environment (virtualenv) using python3.6 in .nox/test-3-6
nox > Command /usr/local/bin/python3 -m virtualenv /tmpfs/src/github/synthtool/.nox/test-3-6 -p python3.6 failed with exit code 1:
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'
nox > Session test-3.6 failed.
nox > Running session test-3.10
nox > Missing interpreters will error by default on CI systems.
nox > Session test-3.10 skipped: Python interpreter 3.10 not found.
nox > Ran multiple sessions:
nox > * lint-3.6: failed
nox > * lint-3.10: skipped
nox > * test-3.6: failed
nox > * test-3.10: skipped
cleanup
```

**Comment by suztomo** [comment]
Thank you

**Comment by suztomo** [comment]
@alicejli Can you add ones under synthtool/gcp/templates/java_library/.kokoro ?

That would resolve the items @kolea2 raised last week.

**Comment by alicejli** [comment]
> @alicejli Can you add ones under synthtool/gcp/templates/java_library/.kokoro ?
> 
> That would resolve the items @kolea2 raised last week.

Good call. Updated!

**Review by SurferJeffAtGoogle — APPROVED** [review]

**Comment by alicejli** [comment]
`owlbot-java-presubmit` test is failing the `new-client-run` build:

```
insertId: "c8dbabe4-d6f7-49fe-9ada-e8beea6fb9e8-612"
labels: {2}
logName: "projects/repo-automation-bots/logs/cloudbuild"
receiveTimestamp: "2023-07-17T17:43:32.285174411Z"
resource: {2}
severity: "INFO"
textPayload: "Step #3 - "new-client-run": TypeError: Descriptors cannot not be created directly."
timestamp: "2023-07-17T17:43:31.754014551Z"
...
insertId: "c8dbabe4-d6f7-49fe-9ada-e8beea6fb9e8-613"
labels: {2}
logName: "projects/repo-automation-bots/logs/cloudbuild"
receiveTimestamp: "2023-07-17T17:43:32.285174411Z"
resource: {2}
severity: "INFO"
textPayload: "Step #3 - "new-client-run": If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0."
timestamp: "2023-07-17T17:43:31.754015901Z"
---
Step #3 - "new-client-run": If you cannot immediately regenerate your protos, some other possible workarounds are:
2023-07-17 13:43:31.754 EDT
Step #3 - "new-client-run": 1. Downgrade the protobuf package to 3.20.x or lower.
2023-07-17 13:43:31.754 EDT
Step #3 - "new-client-run": 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

**Pull request merged**
