### PR TITLE
chore: update Node.js version in legacy installation example

### PR DESCRIPTION
**Pull request by sasakie**
Update version from 8 to 10 in the legacy installation example because Node.js 10 went to maintenance mode for the Google Cloud Node.js SDK on March 31, 2022.

### CODE REVIEW

**Comment by parthea** [comment]
Assigning to @sofisl currently on rotation

**Comment by parthea** [comment]
Assigning to @SurferJeffAtGoogle currently on rotation

**Comment by bcoe** [comment]
Thanks for the patch @sasakie 🥳 , we'll land this as @sofisl works on the Node 12 migration over the next couple weeks.

**Comment by SurferJeffAtGoogle** [comment]
Closed due to inactivity.

**Pull request closed without merging**
