### PR TITLE
build: remove codecov.io

### PR DESCRIPTION
**Pull request by elharo**
toward #1055 

This is a start. there might be more we need to remove.

### CODE REVIEW

**Review by chingor13 — CHANGES_REQUESTED** [review]
https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/java_library/.kokoro/build.sh#L110-L113 is also important for kokoro, or it may fail a few builds because its necessary credentials are being revoked here

**Comment by elharo** [comment]
Done. PTAL @chingor13

**Review by elharo — COMMENTED** [review]
PTAL

**Comment by bcoe** [comment]
@elharo @chingor13, we've removed the internal codecov bash script, making it a noop for the time being which references the internal bug We've also rolled out changes for Node.js already removing the Codecov action.

Could we make a smaller PR that just removes Codecov from the Java GitHub actions?

**Comment by bcoe** [comment]
@elharo @chingor13, we've removed the internal codecov bash script, making it a noop for the time being which references the internal bug We've also rolled out changes for Node.js already removing the Codecov action.

Could we make a smaller PR that just removes Codecov from the Java GitHub actions?

**Comment by bcoe** [comment]
Codecov.io has been removed from Node.js/Java GitHub actions, and from kokoro jobs that were reporting to codecov.io.

**Pull request closed without merging**
