### PR TITLE
chore: upgrade native image checks to graalvm-22.3.0 

### PR DESCRIPTION
**Pull request by mpeddada1**

### CODE REVIEW

**Review by suztomo — APPROVED** [review]
I see 22.3.0 tag is not read yet.

Screen Shot 2022-11-28 at 4 04 54 PM

**Comment by suztomo** [comment]
I guess it takes few hours. I see https://github.com/googleapis/testing-infra-docker/pull/259 is merged.

**Comment by mpeddada1** [comment]
Yup, adding `do-not-merge` until 22.3.0 is ready and verified with https://github.com/googleapis/java-bigquery/pull/2427

**Comment by mpeddada1** [comment]
The tagged image is up and has been tested in https://github.com/googleapis/java-bigquery/pull/2427

**Pull request merged**
