### PR TITLE
build: add config .gitattributes

### PR DESCRIPTION
**Pull request by summer-ji-eng**
add `.gitattributes` into node template to fix windows linter fail on end of line break issue #464

### CODE REVIEW

**Comment by bcoe** [comment]
> [CHANGE ME] PRs. @bcoe should we do a hammer PR firs

This should no longer be needed with @SurferJeffAtGoogle's work, changes to synthtool will show up with whatever commit message we use carried over.

I would just change this to:

> build: add config .gitattributes perhaps

**Comment by summer-ji-eng** [comment]
Try to understand `I would like us to flag the protos directory broadly as "generated" code, so linguist stops counting most of our repos as JavaScript. Turns out, you modify .gitattributes to do that! Figured 92 PRs are better than 184.`
Sorry, I guess I missed some context here. Why make modify `.gitattributes` relate to `protos` directory. And `figured 92 PRs` refer to which PR, any links? @JustinBeckwith could you give me more details?

**Comment by JustinBeckwith** [comment]
Heh, so feel free to ignore this for now.  The context:  GitHub shows you the language for a given repository like this:
image
https://github.com/googleapis?q=&type=&language=javascript

It will also show you the language breakdown in the repo page:
image
https://github.com/googleapis/nodejs-firestore

GitHub uses [linguist](https://github.com/github/linguist) to perform this calculation.  In our case - half our repos show as `TypeScript`, the other half `JavaScript`, mostly because of the amount of JavaScript we generate in that `protos` directory.  I would like GitHub to surface these as TypeScript, both for vanity and for tooling purposes.

**Comment by summer-ji-eng** [comment]
@JustinBeckwith thanks for context. It is really helpful.
As I learned from https://github.com/github/linguist#using-gitattributes, `.gitattribtues` file can override `linguist-documentation`, `linguist-language`, `linguist-vendored`, `linguist-generated` and `linguist-detectable` attributes.

So our change should no mess up `linguist`.
Moreover, maybe we could try add 
`protos/*.js linguist-language=Typescript` in `.gitattributes` to tell linguist the client lib repo is typescript project.

Before I merge this PR, maybe we should use one nodejs client library to test. Does nodejs-firestore a good one to test or do you have any other suggestion. LMK. Thanks

**Comment by JustinBeckwith** [comment]
You got it!  Firestore tends to be a little weird compared to our other repositories. I should have picked a better example.  Maybe https://github.com/googleapis/nodejs-scheduler/?

**Comment by summer-ji-eng** [comment]
Cool. Thanks. Will try out on `nodejs-scheduler`

**Comment by summer-ji-eng** [comment]
test on `nodejs-tasks` https://github.com/googleapis/nodejs-tasks/pull/430
it works as expected
**before** add `.gitattributes` the languages in `nodejs-tasks` looks like this:
Screen Shot 2020-06-26 at 2 53 10 PM
**after** merge, current looks like:
Screen Shot 2020-06-26 at 3 11 34 PM

**Pull request merged**
