### PR TITLE
chore(python): rename master_doc to root_doc

### PR DESCRIPTION
**Pull request by parthea**
Rename `master_doc` to `root_doc` in python templates. See sphinx docs:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-root_doc

### CODE REVIEW

**Comment by tswast** [comment]
Is Version 4 of Sphinx required for this? I recall we used to lock to an older Sphinx. I guess not anymore, seeing as https://github.com/googleapis/python-kms/pull/166 has a passing build?

**Comment by dandhlee** [comment]
@tswast The old version was pinned because the old `sphinx-docfx-yaml` required sphinx version lower than 2 due to an incompatibility bug. With the new `gcp-sphinx-docfx-yaml` I don't think it's strictly required that it's Sphinx version 4 but allows us to use a much newer version.

**Comment by parthea** [comment]
We've pinned to sphinx 4.0.1 in the templated noxfile [here](https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/noxfile.py.j2#L210). I'll keep an eye out for any failures before merging this change in downstream repos.

**Review by tswast — APPROVED** [review]

**Review by busunkim96 — APPROVED** [review]

**Comment by tseaver** [comment]
@parthea for the sake of reducing bot scream, can we please do the replacement of `master` in templated files in a single PR (i.e., merge this change with PR #1188)?

**Pull request closed without merging**
