### PR TITLE
fix: re-enable obsolete tracking with a new strategy

### PR DESCRIPTION
**Pull request by SurferJeffAtGoogle**
old strategy: observe file timestamps to see which files were touched
new strategy: use watchdog to observe every file system event

Control tracking obsolete files with an environment variable.

Fixes https://github.com/googleapis/synthtool/issues/216

### CODE REVIEW

**Comment by SurferJeffAtGoogle** [comment]
Here's the output from an example run:
https://github.com/googleapis/google-cloud-ruby/pull/7049/files#diff-6affd48be461b5ccaa75e24a0c8f4c5c

**Comment by SurferJeffAtGoogle** [comment]
ping @chingor13

**Comment by chingor13** [comment]
It's hard to tell by reading code, but this will be able to catch files that are generated but not updated (because the file date has been touched, but `git diff` won't see the change)?

**Comment by SurferJeffAtGoogle** [comment]
> It's hard to tell by reading code, but this will be able to catch files that are generated but not updated (because the file date has been touched, but `git diff` won't see the change)?

If my understanding is correct, it will even catch files that are generated and the date has been left unchanged, which happens when you use the OS's copy command.

**Pull request merged**
