### PR TITLE
docs: correct spelling of "targetting"

### PR DESCRIPTION
**Pull request by jainsamyak**

### CODE REVIEW

**Comment by jainsamyak** [comment]
Reference to original issue here: https://github.com/googleapis/google-cloud-node/issues/3019
Changes made as propsed by @JustinBeckwith https://github.com/googleapis/nodejs-talent/pull/266#pullrequestreview-531458213

Thanks.

**Review by SurferJeffAtGoogle — APPROVED** [review]

**Comment by bcoe** [comment]
I would like to wait until we've caught up on a current hiccup related to auto-generated PRs from the generator, before we merge this.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@jainsamyak thank you for the contribution.

**Comment by jainsamyak** [comment]
@bcoe thank you! It's the least I could've done, look forward t more..

**Pull request merged**
