### PR TITLE
chore(java): update dependencies in java requirements file

### PR DESCRIPTION
**Pull request by mpeddada1**

### CODE REVIEW

**Comment by suztomo** [comment]
Can you ensure that there's a check that runs pip install for the dependencies?

**Comment by mpeddada1** [comment]
Yes, that's a good idea. Was also wondering about this. Will create a small downstream check to check that runs the install command in python 3.6.

**Comment by suztomo** [comment]
Mridula is going to get help from Jeff.

**Comment by suztomo** [comment]
If the aforementioned check requires time, we can make it later (assuming you confirm `pip install` works for this pull request). When I asked, I assumed it's just adding a section in ".github/workflow/ci.yaml". Apparently this repository does not use GitHub Actions.

**Comment by mpeddada1** [comment]
True. We can try using the existing `owlbot-java-presubmit` job to verify that the `pip install` command works successfully in Python 3.6.

**Comment by mpeddada1** [comment]
The presubmit check has beeing taken into account:
```
Step #9: Successfully installed attrs-22.1.0 cachetools-4.2.4 certifi-2022.9.24 cffi-1.15.1 charset-normalizer-2.0.12 click-8.0.4 colorlog-6.7.0 cryptography-38.0.3 gcp-docuploader-0.6.4 gcp-releasetool-1.9.1 google-api-core-2.8.2 google-auth-2.14.0 google-cloud-core-2.3.1 google-cloud-storage-2.0.0 google-crc32c-1.3.0 google-resumable-media-2.3.3 googleapis-common-protos-1.56.3 idna-3.4 importlib-metadata-4.8.3 jeepney-0.7.1 jinja2-3.0.3 keyring-23.4.1 markupsafe-2.0.1 packaging-21.3 protobuf-3.19.5 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.21 pyjwt-2.4.0 pyparsing-3.0.9 pyperclip-1.8.2 python-dateutil-2.8.2 requests-2.27.1 rsa-4.9 secretstorage-3.3.3 six-1.16.0 typing-extensions-4.1.1 urllib3-1.26.12 zipp-3.6.0
```

**Review by suztomo — APPROVED** [review]
I see pip install succeed. thank you.

Screen Shot 2022-11-07 at 10 43 59 AM

**Pull request merged**
