### PR TITLE
docs: add dependency installation to CONTRIBUTING

### PR DESCRIPTION
**Pull request by texasmichelle**
add .DS_Store to .gitignore

Originally surfaced as problems setting up my environment in googleapis/nodejs-translate ([#424](https://github.com/googleapis/nodejs-translate/pull/424)).

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@bcoe do you want to do a hammer PR first?  @SurferJeffAtGoogle if we merge this as is, it would trigger *82* PRs with bad titles in the evening that need cleaning up.  Just mentioning this to frame the template part of the context-aware-commits work :)

**Comment by texasmichelle** [comment]
🔨 PR? What would trigger so many PRs and why? Is there something I could modify here to prevent that?

**Comment by bcoe** [comment]
@texasmichelle thank you for the contribution :ok_hand: 

@JustinBeckwith @SurferJeffAtGoogle yes, the out of context PRs are a bit annoying, when I've caught up a bit this week I'll use [github-repo-automation](https://github.com/googleapis/github-repo-automation) to deploy this change with nice commit messages.

@SurferJeffAtGoogle this is the type of work I'd love for us to split into a separate bot, which just manages template updates like this potentially, we could split templates into their own project.

**Comment by SurferJeffAtGoogle** [comment]
Michelle, feel free to re-open this PR if you still intend to merge it.

**Comment by texasmichelle** [comment]
I'm not opinionated about these changes going in, but they were waiting on Ben, who suggested I make them here. @bcoe are these still worthwhile?

**Pull request closed without merging**
