### PR TITLE
Use ssh for cloning private repo

### LINKED ISSUE #173: private repo cloning using http and username prompting
Trying to use private repos is prompting for usernames. This fails for 2FA. Perhaps it should be using ssh keys.
```
synthtool   
                                                                                                                                                 
synthtool > Executing /Users/crwilcox/workspace/private-java/google-cloud-clients/google-cloud-spanner/synth.py.
synthtool > Ensuring dependencies.
synthtool > Pulling artman image.
latest: Pulling from googleapis/artman
Digest: sha256:2f6b261ee7fe1aedf238991c93a20b3820de37a343d0cacf3e3e9555c2aaf2ea
Status: Image is up to date for googleapis/artman:latest
synthtool > Cloning private-repo.
Username for 'https://github.com': ^C
```

### PR DESCRIPTION
**Pull request by busunkim96**
Closes #173

### CODE REVIEW

**Comment by theacodes** [comment]
I'm worried this isn't the right solution either. Some of us have setups where they *don't* have ssh keys configured at all.

**Comment by busunkim96** [comment]
Ah I see. So it's possible to do 2FA on the command line with a personal access token + HTTPS *or* SSH...

**Comment by busunkim96** [comment]
The prompt looks like it's working properly. I made a new personal access token and provided it [as the password.](https://help.github.com/articles/accessing-github-using-two-factor-authentication/#authenticating-on-the-command-line-using-https) 

```
synthtool > Cloning googleapis-private.
Username for 'https://github.com': busunkim96
Password for 'https://busunkim96@github.com': 
synthtool > Running generator for google/privacy/dlp/artman_dlp_v2.yaml.
```

**Comment by theacodes** [comment]
Then I think this is working as intended. Maybe we should just update  the docs to mention setting the SSH env var if needed?

**Comment by busunkim96** [comment]
Yes, will do

**Pull request closed without merging**
