### PR TITLE
chore(python): simplify nox steps in CONTRIBUTING.rst

### PR DESCRIPTION
**Pull request by parthea**
This is a follow up to PR #1132 based on feedback from https://github.com/googleapis/python-bigquery-sqlalchemy/pull/191 to simplify the steps to run `nox` in [CONTRIBUTING.rst](https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/CONTRIBUTING.rst).

### CODE REVIEW

**Comment by busunkim96** [comment]
Is it worth capturing in the doc that you can select a single unit test version with `nox -s unit-3.6`? Or is that level of detail not desired?

**Comment by jimfulton** [comment]
I think it;s worthwhile to show a single unit-test version example, as we do for system tests.

**Comment by parthea** [comment]
@busunkim96 @jimfulton I've simplified the instructions. PTAL.

**Review by SurferJeffAtGoogle — APPROVED** [review]

**Comment by parthea** [comment]
Wait for #1137 to be merged first as the body of this PR contains relative links which won't make sense in downstream repos.

**Review by busunkim96 — APPROVED** [review]

**Pull request merged**
