### PR TITLE
fix: clarify the gax-nodejs usage in README

### PR DESCRIPTION
**Pull request by summer-ji-eng**
Address issue #1351

### CODE REVIEW

**Review by tmatsuo — APPROVED** [review]
LG, @bcoe might want to add a simple snippet.

**Review by bcoe — APPROVED** [review]
I think that this looks like a good addition to the docs, a good reason not to add a sample (which I'd originally suggested) is that the methods vary a bit on a client by client basis, and it might confuse a customer if we document a method that's not on the client.

A suggestion, since `timeout` is one of the more common settings we need to tweak for customers, perhaps we could add an example specifically for timeouts to:

https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md

**Comment by parthea** [comment]
Assigning to @SurferJeffAtGoogle currently on rotation

**Comment by bcoe** [comment]
@SurferJeffAtGoogle this will create 150 PRs when merged, so will leave to you whether you choose to merge this week or wait for me to do so during my rotation.

**Pull request merged**
