### PR TITLE
nodejs: add test_project arg for templates

### PR DESCRIPTION
**Pull request by kinwa91**
...to specify the project to use when running system/samples-tests

### CODE REVIEW

**Comment by theacodes** [comment]
I am *extremely* surprised that this is exposed/hardcoded at all. Can we just treat this like a secret and have kokoro/circle inject the environment variable?

**Comment by kinwa91** [comment]
Let's just go with hard-coding the default here - it's not trivial to add the environment to all nodejs- repositories on Circle and it's even more effort for Kokoro with GCS or Keystore strategies.

**Comment by theacodes** [comment]
@kinwa91 if you still need this, can you resolve the conflicts?

**Comment by kinwa91** [comment]
I think this is ready @theacodes

**Pull request merged**
